name: sortedmap
description: A map of objects which can be sorted and filtered on both their key and value
version: 0.5.5
homepage: https://github.com/appsup-dart/sortedmap
repository: https://github.com/appsup-dart/sortedmap
funding:
 - https://github.com/sponsors/rbellens


environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.16.5
  benchmark_test: ^0.1.1+2
  lints: ^6.0.0
  quiver: ^3.0.0
  melos: ^7.0.0

melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false
      hooks:
        pre:
          exec: dart test -j 1
