name: sortedmap
description: A map of objects which can be sorted and filtered on both their key and value
version: 0.4.2+1
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/sortedmap

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.5
  benchmark_harness: ^2.0.0
  pedantic: ^1.11.0
